### ISSUE TITLE
tiny Yolo model 测试问题

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle.js#11]
按照例子里https://github.com/PaddlePaddle/Paddle.js/tree/master/src/paddle的说明，起tinyYolo服务，报错：

Server running at http://localhost:1234 
🚨  /home/aistudio/Paddle.js/examples/tinyYolo/index.es6:4:15: Cannot resolve dependency '../../src/feed/imageFeed' at '/home/aistudio/Paddle.js/src/feed/imageFeed'
  2 | import 'babel-polyfill';
  3 | import Paddle from '../../src/paddle/paddle';
> 4 | import IO from '../../src/feed/imageFeed';

将aistudio@jupyter-141218-528471:~/Paddle.js/src/feed$  目录下的一个imageFeed.es6文件改名为不带后缀，不再报错。

但是在使用chrome和safari两种浏览器里，均只能看到上传照片按钮，上传照片后没有任何输出。 不知道什么原因。。

**Comment by haozech** [comment]
> 按照例子里[https://github.com/PaddlePaddle/Paddle.js/tree/master/src/paddle的说明，起tinyYolo服务，报错：](https://github.com/PaddlePaddle/Paddle.js/tree/master/src/paddle%E7%9A%84%E8%AF%B4%E6%98%8E%EF%BC%8C%E8%B5%B7tinyYolo%E6%9C%8D%E5%8A%A1%EF%BC%8C%E6%8A%A5%E9%94%99%EF%BC%9A)
> 
> Server running at http://localhost:1234
> 🚨 /home/aistudio/Paddle.js/examples/tinyYolo/index.es6:4:15: Cannot resolve dependency '../../src/feed/imageFeed' at '/home/aistudio/Paddle.js/src/feed/imageFeed'
> 2 | import 'babel-polyfill';
> 3 | import Paddle from '../../src/paddle/paddle';
> 
> > 4 | import IO from '../../src/feed/imageFeed';
> 
> 将aistudio@jupyter-141218-528471:~/Paddle.js/src/feed$ 目录下的一个imageFeed.es6文件改名为不带后缀，不再报错。
> 
> 但是在使用chrome和safari两种浏览器里，均只能看到上传照片按钮，上传照片后没有任何输出。 不知道什么原因。。

你好，目前github repo中没有模型文件，您可以使用我们提供的模型转换工具将自己的paddle模型转换为paddle.js模型后放入目录以读取。
以tinyTolo为例，根据index.es6中的设置
`const modelPath = {
    'tinyYolo': 'model/tinyYolo'
};`
模型文件需要放入根目录/dist/model/tinyYolo。
关于模型转换工具的更多信息可以看[README](https://github.com/PaddlePaddle/Paddle.js/blob/master/tools/ModelConverter/README_cn.md)

**Comment by zhongkai** [comment]
close this issue cause new version released
