### ISSUE TITLE
paddlejs引入模型报错

### ISSUE THREAD

**Issue by liuna471658955** [PaddlePaddle/Paddle.js#116]

**Comment by liuna471658955** [comment]
按照官网视频的例子，模型是自己转的paddleocr的识别模型，但是加载模型的时候报错了，有人可以解答一下谁为什么吗

**Comment by JingyuanZhang** [comment]
目前还没有支持 ocr 模型结构，先给一下模型地址吧~ 我们排期支持一下~

**Comment by liuna471658955** [comment]
@JingyuanZhang https://github.com/PaddlePaddle/PaddleOCR ,这个就是paddleOCR的模型，多谢啦

**Comment by JingyuanZhang** [comment]
目前 paddleOCR detect 模型已支持，可以使用 sdk ：https://github.com/PaddlePaddle/Paddle.js/tree/master/packages/paddlejs-models/ocrdetection

**Comment by JingyuanZhang** [comment]
最新 ocr 文本识别全流程 model 已上线 
https://github.com/PaddlePaddle/Paddle.js/tree/master/packages/paddlejs-models/ocr
欢迎使用
