### ISSUE TITLE
Paddle.js yolo例子缺少图片文件

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle.js#12]
启动服务后报错：

(base) ubuntu@ip-172-31-23-98:~/github/Paddle.js/examples/yolo$ npm run yolo

> paddel-web@1.0.0 yolo /home/ubuntu/github/Paddle.js
> parcel ./examples/yolo/index.html

Server running at http://localhost:1234 
🚨  /home/ubuntu/github/Paddle.js/examples/yolo/pic.png: ENOENT: no such file or directory, open '/home/ubuntu/github/Paddle.js/examples/yolo/pic.png'
Error: ENOENT: no such file or directory, open '/home/ubuntu/github/Paddle.js/examples/yolo/pic.png'

浏览器里打开xxxx：1234 网页，也是报错信息：

/home/ubuntu/github/Paddle.js/examples/yolo/pic.png: ENOENT: no such file or directory, open '/home/ubuntu/github/Paddle.js/examples/yolo/pic.png'

**Comment by zhongkai** [comment]
close this issue cause new version released
