### ISSUE TITLE
前端小白求手势识别完整demo

### ISSUE THREAD

**Issue by luqihui** [PaddlePaddle/Paddle.js#144]
https://aistudio.baidu.com/aistudio/education/lessonvideo/1303026
这个视频的手势识别完整demo有吗，前端小白，做毕设想学学怎么用。

**Comment by Leoqh96** [comment]
道友您好，可以提供下课程名称吗，我这边打开链接是空的呢

**Comment by JingyuanZhang** [comment]
手势识别完整demo
https://github.com/PaddlePaddle/Paddle.js/tree/master/packages/paddlejs-models/gesture
