### ISSUE TITLE
PaddleDetection训练的ppyolo模型转Paddle.js模型失败，无输出

### ISSUE THREAD

**Issue by luqihui** [PaddlePaddle/Paddle.js#145]
我用PaddleDetection训练的PPYolo模型export_model成_model_和_params_之后，再用Paddle.js的convertToPaddleJsModel转换模型后，指定的output文件夹内为空，但转换过程的print显示success，没有转换后的结果。

**Comment by YuWang-CV** [comment]
同样的问题，请问您解决了吗？

**Comment by luqihui** [comment]
> 同样的问题，请问您解决了吗？

没有解决…

**Comment by JingyuanZhang** [comment]
converter 模块已更新
辛苦pip install  paddlejsconverter 
或者使用最新 paddlejsconverter 查看，看一下问题
