### ISSUE TITLE
三个Demo 使用npm或者yarn都不能成功安装依赖

### ISSUE THREAD

**Issue by ralph0813** [PaddlePaddle/Paddle.js#156]
三个Demo 使用npm或者yarn都不能成功安装依赖：
npm version: 7.10.0
node version: v16.0.0
yarn version: 1.22.10
![641621339776_ pic](https://user-images.githubusercontent.com/50762307/118649588-3ef58080-b816-11eb-897f-7e1900e5ca07.jpg)
![661621340093_ pic](https://user-images.githubusercontent.com/50762307/118649609-4583f800-b816-11eb-84f5-c3982e290be2.jpg)
![671621340116_ pic](https://user-images.githubusercontent.com/50762307/118649615-487ee880-b816-11eb-851c-7823c8ae4d7e.jpg)

**Comment by Leoqh96** [comment]
道友您好，可以试试npm代理到百度域下安装

**Comment by Leoqh96** [comment]
道友您好，可以试试将npm代理挂到百度域下进行安装

**Comment by Leoqh96** [comment]
道友您好可以试试在百度域下安装
npm --registry http://registry.npm.baidu-int.com i

**Comment by JingyuanZhang** [comment]
gitee 代码库已更新 https://gitee.com/paddlepaddle/Paddle.js
