### ISSUE TITLE
引入微信小程序时报错

### ISSUE THREAD

**Issue by 1solo** [PaddlePaddle/Paddle.js#167]
引入微信小程序时报错Cannot read property 'userAgent' of undefined，将其注释后其他方法也报错。
![图片](https://user-images.githubusercontent.com/55135642/120621877-e1f1ff80-c490-11eb-833d-4b5840e9a930.png)

**Comment by Leoqh96** [comment]
道友您好，可以再给出详细一点的说明嘛，感谢感谢
