### ISSUE TITLE
引入paddlejs-backend-cpu回报找不到错误

### ISSUE THREAD

**Issue by Xanthippe666** [PaddlePaddle/Paddle.js#169]
您好，正在用Vue.js 开发Web应用的时候，想引用Paddle.js的CPU版本然后发现会报错。

<img width="960" alt="screenshot2" src="https://user-images.githubusercontent.com/60343141/120951947-984d3180-c77c-11eb-8502-f76e8c0b966c.png">

测试了一下然后发现稍微改一下引用就可以了 （后面加上/lib)

<img width="960" alt="screenshot3" src="https://user-images.githubusercontent.com/60343141/120951998-b74bc380-c77c-11eb-9c97-225eaeaf4a3d.png">

我感觉在npm package里面，引入链接有BUG? 麻烦了，谢谢

**Comment by Leoqh96** [comment]
您好，已定位问题原因，后续会尽快修复哈，感谢您的宝贵建议~

**Comment by Leoqh96** [comment]
已更新，可更新本地依赖，引入方式为' import '@paddlejs/paddlejs-backend-cpu'; '
