### ISSUE TITLE
预测结果始终不变

### ISSUE THREAD

**Issue by realeve** [PaddlePaddle/Paddle.js#172]
![image](https://user-images.githubusercontent.com/448208/121782764-c21fb180-cbdd-11eb-9bcd-78ab8b8ac626.png)

使用 paddleClass训练了一个多分类模型（5个分类），在python后端正常，转成js的版本后，预测结果始终一样，数据预处理看上去正常

**Comment by JingyuanZhang** [comment]
document.getElementById('photo') 返回的 dom 类型是什么？

**Comment by realeve** [comment]
@JingyuanZhang 
![image](https://user-images.githubusercontent.com/448208/126119611-25a6eb3d-651c-4a6a-8367-9c0ad8237cd2.png)

按照这里的demo来实现的 
 https://github.com/PaddlePaddle/Paddle.js/blob/bde871f1064d2f5559be6a0cac23c0c17332f6cd/packages/paddlejs-core/README_cn.md

```ts
// Import @paddlejs/paddlejs-core
import { Runner } from '@paddlejs/paddlejs-core';
// Import the registered WebGL backend.
import '@paddlejs/paddlejs-backend-webgl';

const runner = new Runner({
    modelPath: '/model/mobilenetv2', // model path, e.g. http://xx.cc/path, http://xx.cc/path/model.json, /localModelDir/model.json, /localModelDir
    feedShape: { // input shape
        fw: 256,
        fh: 256
    },
    fill?: '#fff' // fill color when resize image, default value is #fff
});

// init runner
await runner.init();
// predict and get result
const res = await runner.predict(mediadata, callback?);
```

这里 没写 mediadata 到底是一个dom还是其它的什么类型，dom 是  canvas还是img，如果是数据的话是不是需要转到0-1的区间内。

**Comment by JingyuanZhang** [comment]
media data 可以 HTMLImageElement  | HTMLVideoElement | HTMLCanvasElement

**Comment by realeve** [comment]
按照上面这样，给的是 HTMLImageElement ，但结果好像没对。

**Comment by JingyuanZhang** [comment]
你的模型可以发我一下吗？
