### ISSUE TITLE
模型文件云存储后无法访问的问题

### ISSUE THREAD

**Issue by zoulu995** [PaddlePaddle/Paddle.js#174]
```js
async function load() {
    const path = 'https://paddlejs.cdn.bcebos.com/models/mobileNetV2';
    await mobilenet.load({
        path,
        fileCount: 3,
        mean: [0.485, 0.456, 0.406],
        std: [0.229, 0.224, 0.225]
    }, map);
    document.getElementById('loading')!.style.display = 'none';
}
```
官方demo中的模型文件存储在上述path地址：https://paddlejs.cdn.bcebos.com/models/mobileNetV2
我自己转化了一个模型后，采用百度云的BOS对象存储服务后的地址：https://paddlejs2.bj.bcebos.com/tianjiao_mobilenetv2
为啥替换后不能正常访问呢？（本地测模型没有问题，应该就是模型地址加载的问题，求大佬帮忙看看！

**Comment by Leoqh96** [comment]
道友您好，本地试了一下您的这个云模型地址，貌似存在跨域问题，无法请求成功，

**Comment by Leoqh96** [comment]
道友你好，本地起服务试了一下您的这个存储地址，控制台报错貌似存在跨域问题，导致无法请求模型
![image](https://user-images.githubusercontent.com/48266113/125033456-e7f78380-e0c1-11eb-8e03-dfc2a3077fa3.png)
如果您使用的是百度云对象云存储服务，可以参考以下思路解决跨域问题
https://cloud.baidu.com/doc/BOS/s/Dk6kqw1g8

**Comment by zoulu995** [comment]
> 道友你好，本地起服务试了一下您的这个存储地址，控制台报错貌似存在跨域问题，导致无法请求模型
> ![image](https://user-images.githubusercontent.com/48266113/125033456-e7f78380-e0c1-11eb-8e03-dfc2a3077fa3.png)
> 如果您使用的是百度云对象云存储服务，可以参考以下思路解决跨域问题
> https://cloud.baidu.com/doc/BOS/s/Dk6kqw1g8

感谢，以解决！！！
