### ISSUE TITLE
是否支持WebWorker OffscreenCanvas

### ISSUE THREAD

**Issue by HighCWu** [PaddlePaddle/Paddle.js#18]
如题，支持WebWorker的OffscreenCanvas可以避免主界面的堵塞。
进行源码搜索时并没有见到相关的实现代码，所以在此提出建议。

**Comment by luan007** [comment]
use options.el as a starting point maybe. tested with yolo example & confirmed working.

``` javascript
const paddle = new Paddle({
            urlConf: MODEL_CONFIG,
            options: {
                el: new OffscreenCanvas(512, 512),
            }
});
```

however to fully unblock the page, paddle.js needs live completely in webworker,
any examples / doc would be helpful.

**Comment by HighCWu** [comment]
thank you for your reply. if paddle.js can run on webworker totally, it will be very nice for users.

**Comment by Tanner-sun** [comment]
so 

> use options.el as a starting point maybe. tested with yolo example & confirmed working.
> 
> ```js
> const paddle = new Paddle({
>             urlConf: MODEL_CONFIG,
>             options: {
>                 el: new OffscreenCanvas(512, 512),
>             }
> });
> ```
> 
> however to fully unblock the page, paddle.js needs live completely in webworker,
> any examples / doc would be helpful.

so does paddle.js can live completely in webworker?  in web condition we do not want the calculation to block the page especially used for C user

**Comment by luan007** [comment]
@Tanner-sun in my snippet: no. It only shows OffscreenCanvas can be used without monkey patching the lib.
To put paddle.js completely in worker you might need to ref paddle.js with
``` javascript
importScript(..);
```
in separate worker.js file, where common dom env variables are not present (e.g window / document / createElement).
thus the lib will work if none of which are being used.

**things to consider though**
frequent communication between worker & main thread (like transferring image data at 60fps) can cause major performance issue.

there's this tf.js issue related to this for your reference.

https://github.com/tensorflow/tfjs/issues/102

**Comment by zhongkai** [comment]
close this issue cause new version released
