### ISSUE TITLE
如何改变example humanStream的backend

### ISSUE THREAD

**Issue by clannadxiaohei** [PaddlePaddle/Paddle.js#186]
您好，我运行humanStream时遇到了以下错误：

`Uncaught (in promise) TypeError: Failed to execute 'getAttribLocation' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLProgram'.`

本地没有GPU，请问这需要更改backend吗？如果需要请问如何修改？

**Comment by JingyuanZhang** [comment]
你用的是什么设备？目前其他 backend op 暂未完全支持 humanseg 模型，所以暂时还不能使用其他backend

**Comment by clannadxiaohei** [comment]
@JingyuanZhang 用的win10，机器没有GPU。我看代码humanseg模型和mobilenet模型的backend都是webgl，为什么humanseg模型无法成功，是因为需要硬件支持吗？

**Comment by JingyuanZhang** [comment]
对~ 目前的方案是 webgl backend，需要显卡支持~
你试一下 在 控制台输入，看一下有无报错，或者有什么 log 信息输出
const canvas = document.createElement('canvas');
const gl = canvas.getContext('experimental-webgl');
const debugInfo = gl.getExtension('WEBGL_debug_renderer_info');
console.log(gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL));

**Comment by clannadxiaohei** [comment]
@JingyuanZhang log信息:

`ANGLE (NVIDIA, NVIDIA Quadro M2000 Direct3D11 vs_5_0 ps_5_0, D3D11-23.21.13.8816)`

**Comment by JingyuanZhang** [comment]
那可以使用 webgl backend，你安装的 @paddlejs-models/humanseg  版本号是多少~
