### ISSUE TITLE
小程序报错TypeError: Cannot read property 'userAgent' of undefined

### ISSUE THREAD

**Issue by zhaixiyun** [PaddlePaddle/Paddle.js#192]
**paddle npm版本**
"paddlejs": "^1.0.17"

**paddle微信小程序插件版本**
```
"paddlejs-plugin": {
      "version": "0.0.3",
      "provider": "wx7138a7bb793608c3"
    }
```

**代码参考**
https://blog.csdn.net/weixin_45449540/article/details/108114307

**报错信息**
开始是app.js报错，关闭es6转es5选项之后报错消失

之后打开相关功能页面报错
Cannot read property 'userAgent' of undefined

**或者能否提供一个可以跑通的示例，搜索小程序示例只能搜到上面一个示例**

**Comment by zhaixiyun** [comment]
找到问题了已经，小程序环境下没有navigator
报错文件是minipargram_npm/paddlejs/index.js
```
this.isMobile = navigator.userAgent.indexOf("iPhone") >= 0 ||
                        navigator.userAgent.indexOf("Android") >= 0
```

**Comment by JingyuanZhang** [comment]
小程序 demo 已提供
https://github.com/PaddlePaddle/Paddle.js/tree/master/packages/paddlejs-examples/clasGame
