### ISSUE TITLE
我想问下paddlejs humanStream demo运行时提示WebGL: INVALID_OPERATION: texImage2D: ArrayBufferView not big enough for request是什么原因？

### ISSUE THREAD

**Issue by im-waiting** [PaddlePaddle/Paddle.js#205]
还有一句是：[WDS] Live Reloading enabled.

**Comment by BenAnn** [comment]
你是用的是packages/paddlejs-examples/humanStream吗？如何操作能复现呢？

**Comment by wkmcoder** [comment]
是用packages/paddlejs-examples/humanStream这个工程，我是直接安装完依赖后，在台式机上运行的，然后就提示这个警告，页面一直显示loading中
![QQ截图20210818195257](https://user-images.githubusercontent.com/21035439/129893545-cbb183ce-eb51-4537-9d63-1a7b89f38801.png)

**Comment by BenAnn** [comment]
你这边是windows？具体系统版本和node版本是什么呢？

**Comment by wkmcoder** [comment]
win10  20H2  64位  专业版，nod版本v10.16.3

**Comment by JingyuanZhang** [comment]
这个应该是因为 camera 的数据没有权限获取导致，辛苦确认访问 https 并且可以开启 摄像头使用认证
