### ISSUE TITLE
通过finetune训练的mobienet，通过转换工具后softmax变成了1000分类

### ISSUE THREAD

**Issue by fuchun107** [PaddlePaddle/Paddle.js#22]
通过finetune训练的mobienet模型，在python上运行结果是自己的分类的20种。
但是通过转换工具生成的model.json中softmax等于imagenet的1000分类，js运行得到的结果也是1000分类
        {
            "name": "softmax_0.tmp_0", 
            "persistable": false, 
            "shape": [
                1000
            ]
        }
这是什么情况？
模型训练是在aistudio上通过paddleclas finetune的，训练完成后通过predict出现的结果是正确的。

**Comment by yueshuangyan** [comment]
可以先用netron可视化工具check一下待转换模型的softmax_0.tmp_0的shape信息是否正确
![image](https://user-images.githubusercontent.com/20450873/87640450-5177d700-c779-11ea-8e50-c26bd0031e97.png)

**Comment by zhongkai** [comment]
close this issue cause new version released
