### ISSUE TITLE
前端模型无法正常加载

### ISSUE THREAD

**Issue by adaxiadaxi** [PaddlePaddle/Paddle.js#23]
src.a2b27638.js:122 Uncaught (in promise) RangeError: byte length of Float32Array should be a multiple of 4
    at new Float32Array (<anonymous>)
    at src.a2b27638.js:122
    at Array.forEach (<anonymous>)
    at src.a2b27638.js:122

定位 src/index.js第40行，前端模型无法加载

**Comment by yueshuangyan** [comment]
可在浏览器的network中检查一下模型文件是否有请求到，检查一下模型的路径。如果是Paddle.js的examples环境，静态资源路径是dist目录下。可以补充一下工程环境信息进一步帮忙排查。

**Comment by zhongkai** [comment]
close this issue cause new version released
