### ISSUE TITLE
微信小程序引入paddlejs版本1.0.17出错

### ISSUE THREAD

**Issue by shubihu** [PaddlePaddle/Paddle.js#244]
adaptPadjsV1 is not defined;at App lifeCycleMethod onLaunch function
ReferenceError: adaptPadjsV1 is not defined

![image](https://user-images.githubusercontent.com/36021958/140249128-0e9cd0c9-ac89-46a5-8f4a-48d173e851d1.png)

**Comment by JingyuanZhang** [comment]
请问使用 小程序插件了吗？
https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/using.html

**Comment by shubihu** [comment]
![image](https://user-images.githubusercontent.com/36021958/149459726-bd200039-d3bc-4082-bb47-dfe271c76b67.png)
![image](https://user-images.githubusercontent.com/36021958/149459799-d3aeff33-2928-428f-86e5-30866acce360.png)
![image](https://user-images.githubusercontent.com/36021958/149459856-14552f99-4c44-47c0-94b2-3f424794fb96.png)
使用了的，谢谢

**Comment by JingyuanZhang** [comment]
@paddlejs/paddlejs-backend-webgl@1.1.9
@paddlejs/paddlejs-core@2.1.10
用一下最新版本，看一下是否还有报错
