### ISSUE TITLE
小程序调用转换为js可用的模型调用出错

### ISSUE THREAD

**Issue by miriplekwx** [PaddlePaddle/Paddle.js#263]
2.1版本的转换工具得到的模型，加载会报错TypeError: Cannot read property 'length" of undefined
2.0版本的转换工具得到的模型，加载会报错Unhandled promise rejection TypeError: Reduce of empty array with no initial value
前一个问题今年二月就有人提了issues，请问这个有没有什么进展，我该如何解决

**Comment by BenAnn** [comment]
方便提供模型吗？转后后的model.json里是否有ops呢？

**Comment by BenAnn** [comment]
应该是有算子不支持，辛苦在packages/paddlejs-core/src/graph.ts的arrangeMap下加这两行代码
![image](https://user-images.githubusercontent.com/17406160/147078663-21415be3-adfb-4c6b-a2a4-a7eeef3de7c3.png)
在控制台根据打印的index找到weightMap对应的算子，把type告诉我们
![image](https://user-images.githubusercontent.com/17406160/147078934-4b82aab7-d51e-4d97-80d4-5cd44c070451.png)
，我们支持一下
