### ISSUE TITLE
paddlejs-converter转出来的模型，在小程序上报Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by shixibao** [PaddlePaddle/Paddle.js#266]
![image](https://user-images.githubusercontent.com/23250892/146890735-59f3ab77-465d-4901-9152-4578ef643649.png)

**Comment by BenAnn** [comment]
方便提供模型吗？转后后的model.json里是否有ops呢？

**Comment by shixibao** [comment]
> 

![image](https://user-images.githubusercontent.com/23250892/147064902-e7e7805c-ccb8-4bd3-8a5b-e73c72152f90.png)


有ops

**Comment by BenAnn** [comment]
方便在packages/paddlejs-core/src/graph.ts的arrangeMap方法里debugger看下吗？根据报错信息应该是weightMap或者outputsName有问题，我们这边的模型都无法复现，导致无法查

**Comment by shixibao** [comment]
可以给你提供一下模型

**Comment by shixibao** [comment]
> 方便在packages/paddlejs-core/src/graph.ts的arrangeMap方法里debugger看下吗？根据报错信息应该是weightMap或者outputsName有问题，我们这边的模型都无法复现，导致无法查

http://img.yikuaigao.com/download/models/big_model.zip

**Comment by shixibao** [comment]
> 方便在packages/paddlejs-core/src/graph.ts的arrangeMap方法里debugger看下吗？根据报错信息应该是weightMap或者outputsName有问题，我们这边的模型都无法复现，导致无法查

[转化后的模型.zip](https://img.yikuaigao.com/download/models/%E8%BD%AC%E5%8C%96%E5%90%8E%E7%9A%84%E6%A8%A1%E5%9E%8B.zip)

这是用paddlejs-converter 转出来的

**Comment by BenAnn** [comment]
debug发现你的模型中有个yolo_box算子，目前我们还不支持，你可以提issue让我们支持一下

**Comment by shixibao** [comment]
> debug发现你的模型中有个yolo_box算子，目前我们还不支持，你可以提issue让我们支持一下

好的，我需要在PaddlePaddle/Paddle 这个项目下提issue吗？您可以加个我微信吗？wx: sxb7772010 ,沟通方便一些

**Comment by JingyuanZhang** [comment]
缺失算子已安排~预计 本周发布
