### ISSUE TITLE
微信小程序无法引入paddle.js

### ISSUE THREAD

**Issue by SOVLOOKUP** [PaddlePaddle/Paddle.js#27]
<img width="632" alt="微信截图_20200725173720" src="https://user-images.githubusercontent.com/53158137/88453869-84b71600-ce9d-11ea-9ef5-0400a5f7ac74.png">

**Comment by yueshuangyan** [comment]
paddlejs的npm包名为paddlejs,  请安装1.0.4版本及以上的paddlejs npm包试一下。

**Comment by SOVLOOKUP** [comment]
感谢，另外附上微信小程序引入npm的文档：https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html
还有一个问题，微信小程序没有操作dom树的方法，paddlejs有没有针对图像url的predict接口？

**Comment by SOVLOOKUP** [comment]
自问自答，可以用wx.createoffscreencanvas().createimage()创建对象赋予src width height属性 将对象传入predict

**Comment by autowo** [comment]
使用本地开发工具时，可正常使用paddlejs离线预测，真机预览时无法运行预测。
进入真机调试时，报错如下：
`VM22:2 (in promise) MiniProgramError
Cannot read property 'createElement' of undefined
TypeError: Cannot read property 'createElement' of undefined
    at new t (weapp:///miniprogram_npm/paddlejs/index.js:647:50)
    at new t (weapp:///miniprogram_npm/paddlejs/index.js:3742:56)
    at setconfig (weapp:///app.js:83:30)
    at eval (weapp:///app.js:171:7)`
![image](https://user-images.githubusercontent.com/7589716/90689410-9fb15600-e2a2-11ea-8c85-6f35a3d02fa6.png)

**Comment by SOVLOOKUP** [comment]
> 使用本地开发工具时，可正常使用paddlejs离线预测，真机预览时无法运行预测。
> 进入真机调试时，报错如下：
> `VM22:2 (in promise) MiniProgramError Cannot read property 'createElement' of undefined TypeError: Cannot read property 'createElement' of undefined at new t (weapp:///miniprogram_npm/paddlejs/index.js:647:50) at new t (weapp:///miniprogram_npm/paddlejs/index.js:3742:56) at setconfig (weapp:///app.js:83:30) at eval (weapp:///app.js:171:7)`
> ![image](https://user-images.githubusercontent.com/7589716/90689410-9fb15600-e2a2-11ea-8c85-6f35a3d02fa6.png)

微信小程序自己整了一套，没有这些element函数，然后创建离屏canvas也有bug一直没有修复，最新解决方案 : 你需要用输入图片的arraybuffer进行预测，我下周会开源完整demo

**Comment by SOVLOOKUP** [comment]
成品已开源:https://github.com/sovlookup/paddlejsinwechat
