### ISSUE TITLE
paddlejs-converter转出来的模型，在小程序上报错

### ISSUE THREAD

**Issue by HelloLcy** [PaddlePaddle/Paddle.js#270]
把caffe的pose_body_25模型( https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/models ) 转换成小程序可用的模型格式后(转换后的模型地址:  https://anime.qrqy.cn/pdjs/openpose-25-keypoint/model.json ) ,在小程序中运行报错，见下图: 

<img width="750" alt="image" src="https://user-images.githubusercontent.com/19768588/147415986-05b88c14-9f88-4e6b-b0a6-a211297bdf45.png">

**Comment by JingyuanZhang** [comment]
请问 使用 小程序插件了吗？辛苦贴一下 使用的 paddlejs-core 和 paddlejs-backend-webgl 版本

**Comment by JingyuanZhang** [comment]
请用一下beta 
@paddlejs/paddlejs-core@2.1.10-beta.0
@paddlejs/paddlejs-backend-webgl@1.1.9-beta.0

再看一下 报错~
