### ISSUE TITLE
无法修改模型输出尺寸

### ISSUE THREAD

**Issue by a53769** [PaddlePaddle/Paddle.js#289]
如题，基于ocr_det demo 模型初始化时包含入参如下：

```
    detectRunner = new Runner({
        modelPath: './models',
        feedShape: {
            fw: 960,
            fh: 960
        },
        fill: '#fff',
        mean: [0.485, 0.456, 0.406],
        std: [0.229, 0.224, 0.225],
        bgr: true,
    });
    await detectRunner.init();
```

但在实际推理时模型输出尺寸为409600，即640*640，推理代码：
```
    ctx.drawImage(image, x, y, sw, sh);
    const outsDict = await detectRunner.predict(canvas);
```
image为需要转换的图像，ctx来自canvas画布，x, y, sw, sh 为转换后尺寸。 outsDict 长度恒为 409600， 并不符合预期。

**Comment by changy1105** [comment]
ocrdetection model 使用的源模型是 ch_ppocr_mobile_v2.0_det_infer，input shape 为 [1, 3, 640, 640]。demo 里定义的 width 和 height 为 640。
![image](https://user-images.githubusercontent.com/43414102/148949150-e5d61a39-23a7-451a-b675-cbf1adb4d7cc.png)

若需要改变 feedShape，可使用 ocr model，文本检测使用的模型为 ch_PP-OCRv2_det_infer ，input shape 为 [1, 3, 960, 960]，且支持自定义模型文件，feedShape 会根据模型 input shape 自动生成。
![image](https://user-images.githubusercontent.com/43414102/148950133-0cfdca3e-12c1-4101-b32c-6e1f40661a10.png)

**Comment by a53769** [comment]
PaddleOCR的Android 实例工程中使用的也是 ch_ppocr_mobile_v2.0_det_infer 检测模型，且在Android 工程中是可以动态调整输入输出尺寸的（调整到960*960），paddlejs里是不支持这样的调整操作吗，因为 ch_PP-OCRv2_det_infer 模型输出的检测框留白较多，才会想着用前一个模型。

**Comment by a53769** [comment]
在 PaddleOCR 的 Android 工程中也使用的是 ch_ppocr_mobile_v2.0_det_infer ，但是是可以动态调整输入输出尺寸的（调整为960*960），PaddleJs 是有什么限制吗，ocr model 中可以调整尺寸是工程代码的集成方式不一样还是单纯的模型限制。
![image](https://user-images.githubusercontent.com/18340648/149330588-cb10f55c-93a3-4c9c-8012-a4250aadb6f9.png)
代码中的这一段尺寸修改看起来是为了适应自定义模型设置的。
![image](https://user-images.githubusercontent.com/18340648/149330709-ab0464ca-5e89-4088-9d0f-01ee92b553c6.png)
直到产出模型输出，没有对模型输入及输出尺寸的相关修改操作。

模型输出尺寸在paddlejs中是伴随模型结构文件不可变的吗。

感谢大佬解惑。

**Comment by changy1105** [comment]
模型输出尺寸在paddlejs中是伴随模型结构文件不可变的吗。

是的，paddlejs 使用的是 ocr 静态模型，目前固定模型输入输出的shape。动态模型计算已经在排期支持中。
