### ISSUE TITLE
HTMLVideoElement is not defined

### ISSUE THREAD

**Issue by zzkzzk1984** [PaddlePaddle/Paddle.js#338]
代码都跟开源的一样，但是同一台手机，原版的正常识别，但是我的就是报错，不知道为什么
![534af91fc0b91597393f88ee683cebb](https://user-images.githubusercontent.com/23081513/153713907-f2deaf8a-2755-40e8-8416-94ce0baa5ed9.png)

**Comment by guozhenqianga** [comment]
遇到同样的问题
![image](https://user-images.githubusercontent.com/23112360/156150109-b08c816b-c53c-4738-8fd8-23e542bb0fcf.png)

**Comment by JingyuanZhang** [comment]
楼主的应该是因为 没有配置 小程序后台域名白名单

**Comment by JingyuanZhang** [comment]
> 遇到同样的问题 ![image](https://user-images.githubusercontent.com/23112360/156150109-b08c816b-c53c-4738-8fd8-23e542bb0fcf.png)

代码能截下图吗？

**Comment by MayYouBeProsperous** [comment]
我之前也有遇到，报错代码位置在packages/paddlejs-core/src/mediaProcessor.ts的66行

![image](https://user-images.githubusercontent.com/99723454/156169869-fa5c46ec-91d8-4a50-8d24-16418de0b2ea.png)


> > 遇到同样的问题 ![image](https://user-images.githubusercontent.com/23112360/156150109-b08c816b-c53c-4738-8fd8-23e542bb0fcf.png)
> 
> 代码能截下图吗？

我之前也有遇到，报错代码位置在packages/paddlejs-core/src/mediaProcessor.ts的66行
![image](https://user-images.githubusercontent.com/99723454/156169869-fa5c46ec-91d8-4a50-8d24-16418de0b2ea.png)
另外后面代码需要用到CanvasRenderingContext2D的地方还会报错

**Comment by JingyuanZhang** [comment]
> > > 遇到同样的问题 ![image](https://user-images.githubusercontent.com/23112360/156150109-b08c816b-c53c-4738-8fd8-23e542bb0fcf.png)
> > 
> > 
> > 代码能截下图吗？
> 
> 我之前也有遇到，报错代码位置在packages/paddlejs-core/src/mediaProcessor.ts的66行 ![image](https://user-images.githubusercontent.com/99723454/156169869-fa5c46ec-91d8-4a50-8d24-16418de0b2ea.png) 另外后面代码需要用到CanvasRenderingContext2D的地方还会报错

可以贴一下你的代码吗？看看你是怎么调用的

**Comment by MayYouBeProsperous** [comment]
> 代码



> > > > 遇到同样的问题 ![image](https://user-images.githubusercontent.com/23112360/156150109-b08c816b-c53c-4738-8fd8-23e542bb0fcf.png)
> > > 
> > > 
> > > 代码能截下图吗？
> > 
> > 
> > 我之前也有遇到，报错代码位置在packages/paddlejs-core/src/mediaProcessor.ts的66行 ![image](https://user-images.githubusercontent.com/99723454/156169869-fa5c46ec-91d8-4a50-8d24-16418de0b2ea.png) 另外后面代码需要用到CanvasRenderingContext2D的地方还会报错
> 
> 可以贴一下你的代码吗？看看你是怎么调用的

我试试复现一下

**Comment by guozhenqianga** [comment]
> > > 遇到同样的问题 ![image](https://user-images.githubusercontent.com/23112360/156150109-b08c816b-c53c-4738-8fd8-23e542bb0fcf.png)
> > 
> > 
> > 代码能截下图吗？
> 
> 我之前也有遇到，报错代码位置在packages/paddlejs-core/src/mediaProcessor.ts的66行 ![image](https://user-images.githubusercontent.com/99723454/156169869-fa5c46ec-91d8-4a50-8d24-16418de0b2ea.png) 另外后面代码需要用到CanvasRenderingContext2D的地方还会报错

https://github.com/PaddlePaddle/Paddle.js/issues/338#issuecomment-1056090772

**Comment by JingyuanZhang** [comment]
两个同学同时说，有点混了
@guozhenqianga @MayYouBeProsperous  辛苦代码传到 gitee 或者 github 上，我们看一下你们各自的源码

**Comment by SpectrePrediction** [comment]
我也遇到了这个问题，我的代码同样按照demo而来
```python
import * as paddlejs from '@paddlejs/paddlejs-core';
import '@paddlejs/paddlejs-backend-webgl';


const plugin = requirePlugin("paddlejs-plugin");
plugin.register(paddlejs, wx);


export const PaddleJS = new paddlejs.Runner({
  modelPath: 'https://mms-voice-fe.cdn.bcebos.com/pdmodel/clas/common/v4_2_0915',
  feedShape: {
      fw: 224,
      fh: 224
  },
  fill: '#fff',
  targetSize: {
      height: 224,
      width: 224
  },
  mean: [0.485, 0.456, 0.406],
  std:  [0.229, 0.224, 0.225],
  needPreheat: true
});

Page({

  /**
   * 页面的初始数据
   */
  data: {
    buttonText: "请等待",
  },

  /**
   * 通过按钮触发
   */
  test: function(){
   
    let image = "./1.jpg"
    
    PaddleJS.predict(image).then(res =>{
      console.log(res)
    })

  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {
    PaddleJS.init().then(res => {
      this.setData({
        buttonText: " 准备完成"
      })
    })
  },
})
```
我同样开启了取消http合法验证

**Comment by JingyuanZhang** [comment]
> 我使用最新版本似乎会出现这个错误，但当我使用回到旧版本
> 
> ```
> "dependencies": {
>     "@paddlejs/paddlejs-backend-webgl": "1.0.7",
>     "@paddlejs/paddlejs-core": "2.0.7"
>   }
> ```
> 
> 一切正常

也是小程序吗？代码可以提一下吗？

**Comment by JingyuanZhang** [comment]
> > 两个同学同时说，有点混了 @guozhenqianga @MayYouBeProsperous 辛苦代码传到 gitee 或者 github 上，我们看一下你们各自的源码
> > @JingyuanZhang 我把项目提交到gitee了，项目地址：https://gitee.com/guozhenqianga/park.git

收到 @Leoqh96 辛苦跟进一下

**Comment by JingyuanZhang** [comment]
> > 两个同学同时说，有点混了 @guozhenqianga @MayYouBeProsperous 辛苦代码传到 gitee 或者 github 上，我们看一下你们各自的源码
> > @JingyuanZhang 我把项目提交到gitee了，项目地址：https://gitee.com/guozhenqianga/park.git

<img width="660" alt="image" src="https://user-images.githubusercontent.com/10822846/156364711-3feefad5-a4d9-4c29-99a9-8c9b30a25f95.png">
在模型配置处，加一下 webglFeedProcess: true 试试

**Comment by SpectrePrediction** [comment]
添加后解决了这个报错，但是似乎新的问题出现了：模型输出不变，无论如何输入，输出都是一样的

**Comment by JingyuanZhang** [comment]
> 添加后解决了这个报错，但是似乎新的问题出现了：模型输出不变，无论如何输入，输出都是一样的

同学，你的代码要不也提一下？我们看一县文体

**Comment by SpectrePrediction** [comment]
多谢好意，我的代码差不多只有这些 https://github.com/PaddlePaddle/Paddle.js/issues/338#issuecomment-1056396692
他差不多就是demo的样子，我认为没有过多查看的必要，我看到存在一个类似问题的issue，但直到关闭了也没有解决方案

**Comment by JingyuanZhang** [comment]
clasGame 里传的是 cameraFrame 视频帧

**Comment by guozhenqianga** [comment]
@JingyuanZhang 
![image](https://user-images.githubusercontent.com/23112360/156482042-ad40bb38-8327-4977-a56d-5dc8cca73da4.png)
这个版本添加webglFeedProcess: true参数后，不报错了，谢谢

**Comment by JingyuanZhang** [comment]
> @JingyuanZhang ![image](https://user-images.githubusercontent.com/23112360/156482042-ad40bb38-8327-4977-a56d-5dc8cca73da4.png) 这个版本添加webglFeedProcess: true参数后，不报错了，谢谢

好的哈~ 之前小程序插件有升级，由于小程序的特殊性，如果需要传入 HTMLVideoElement/ HTMLImageElement 或者 HTMLCanvasElement 元素预测，需要配置这个参数

**Comment by SpectrePrediction** [comment]
> @SpectrePrediction 你的代码 我看了
> 
> ```
> let image = "./1.jpg"
>     
>     PaddleJS.predict(image).then(res =>{
>       console.log(res)
>     })
> ```
> 
> 不支持 传一个 图片地址 字符串

明白了，但这样的行为也不报错，我尝试修改我的代码，非常感谢

**Comment by JingyuanZhang** [comment]
> > @SpectrePrediction 你的代码 我看了
> > ```
> > let image = "./1.jpg"
> >     
> >     PaddleJS.predict(image).then(res =>{
> >       console.log(res)
> >     })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不支持 传一个 图片地址 字符串
> 
> 明白了，但这样的行为也不报错，我尝试修改我的代码，非常感谢

ok~

**Comment by MayYouBeProsperous** [comment]
> > @JingyuanZhang ![image](https://user-images.githubusercontent.com/23112360/156482042-ad40bb38-8327-4977-a56d-5dc8cca73da4.png) 这个版本添加webglFeedProcess: true参数后，不报错了，谢谢
> 
> 好的哈~ 之前小程序插件有升级，由于小程序的特殊性，如果传入 HTMLVideoElement/ HTMLImageElement 或者 HTMLCanvasElement 元素预测，则需要配置这个参数
劳烦看看我的代码，模仿paddlejs-examples/ocr写的
[https://github.com/MayYouBeProsperous/ocr](url)
尝试添加webglFeedProcess: true参数，会报错：Cannot read property 'fh' of undefined
顺便想问一下，我模型初始化好后，程序内存就占用了四五GB，是正常的吗？谢谢。

**Comment by JingyuanZhang** [comment]
> > > @JingyuanZhang ![image](https://user-images.githubusercontent.com/23112360/156482042-ad40bb38-8327-4977-a56d-5dc8cca73da4.png) 这个版本添加webglFeedProcess: true参数后，不报错了，谢谢
> > 
> > 
> > 好的哈~ 之前小程序插件有升级，由于小程序的特殊性，如果传入 HTMLVideoElement/ HTMLImageElement 或者 HTMLCanvasElement 元素预测，则需要配置这个参数
> 
> 劳烦看看我的代码，模仿paddlejs-examples/ocr写的 [github.com/MayYouBeProsperous/ocr](https://github.com/MayYouBeProsperous/ocr) 尝试添加webglFeedProcess: true参数，会报错：Cannot read property 'fh' of undefined 顺便想问一下，我模型初始化好后，程序内存就占用了四五GB，是正常的吗？谢谢。

收到

**Comment by guozhenqianga** [comment]
@JingyuanZhang 想在小程序调用ocr功能，单独引用@paddlejs-models/ocr使用会报错，paddlejs是否提供有开放的ocr模型链接，demo里面直接引用了，没找到modelPath链接


![image](https://user-images.githubusercontent.com/23112360/156540145-f3644e9e-e98d-4048-85f2-3603e4f43e2f.png)

**Comment by JingyuanZhang** [comment]
> @JingyuanZhang 想在小程序调用ocr功能，单独引用@paddlejs-models/ocr使用会报错，paddlejs是否提供有开放的ocr模型链接，demo里面直接引用了，没找到modelPath链接
> 
> ![image](https://user-images.githubusercontent.com/23112360/156540145-f3644e9e-e98d-4048-85f2-3603e4f43e2f.png)

小程序环境限制了部分 api，没有办法和 针对 web 的 ocr model 保持一致，我们看一下能否提供一版专门针对 小程序的 model sdk

**Comment by JingyuanZhang** [comment]
> > > @JingyuanZhang ![image](https://user-images.githubusercontent.com/23112360/156482042-ad40bb38-8327-4977-a56d-5dc8cca73da4.png) 这个版本添加webglFeedProcess: true参数后，不报错了，谢谢
> > 
> > 
> > 好的哈~ 之前小程序插件有升级，由于小程序的特殊性，如果传入 HTMLVideoElement/ HTMLImageElement 或者 HTMLCanvasElement 元素预测，则需要配置这个参数
> 
> 劳烦看看我的代码，模仿paddlejs-examples/ocr写的 [github.com/MayYouBeProsperous/ocr](https://github.com/MayYouBeProsperous/ocr) 尝试添加webglFeedProcess: true参数，会报错：Cannot read property 'fh' of undefined 顺便想问一下，我模型初始化好后，程序内存就占用了四五GB，是正常的吗？谢谢。

https://github.com/PaddlePaddle/Paddle.js/pull/384

**Comment by guozhenqianga** [comment]
@MayYouBeProsperous 你那个demo我跑了下，程序内存直线飙升，还没init完，就把微信开发工具搞黑屏崩溃了，麻烦问下你是怎么解决这个问题的。
![image](https://user-images.githubusercontent.com/23112360/156683738-3061c122-a022-420f-9d2f-713a4134cb61.png)
这样写也是，微信开发工具直接黑屏，就很尴尬。

**Comment by JingyuanZhang** [comment]
问题 HTMLVideoElement is not defined 问题已结，大家反馈的 ocr 内存溢出的问题，已新开 issue #387  ，我们正在跟进，最新进展会在 #387 更新

**Comment by MayYouBeProsperous** [comment]
> @MayYouBeProsperous 你那个demo我跑了下，程序内存直线飙升，还没init完，就把微信开发工具搞黑屏崩溃了，麻烦问下你是怎么解决这个问题的。 ![image](https://user-images.githubusercontent.com/23112360/156683738-3061c122-a022-420f-9d2f-713a4134cb61.png) 这样写也是，微信开发工具直接黑屏，就很尴尬。

还没解决呢，官方在跟踪 #387
