### ISSUE TITLE
使用OCR的例子和微信小程序的例子结合失败，导入模型无限报错

### ISSUE THREAD

**Issue by zzkzzk1984** [PaddlePaddle/Paddle.js#339]
![image](https://user-images.githubusercontent.com/23081513/153739188-3bb4fcf0-aa67-4bc9-a797-bde948a5b2cb.png)

**Comment by JingyuanZhang** [comment]
由于微信小程序 glsl compiler 不支持 tanh 导致
https://github.com/PaddlePaddle/Paddle.js/pull/349
