### ISSUE TITLE
微信引入paddlejs之后报错 const paddlejs = require('paddlejs');

### ISSUE THREAD

**Issue by richarddddd198** [PaddlePaddle/Paddle.js#35]
当在app.js文件输入“const paddlejs = require('paddlejs');”就提示报错如下图。
<img width="638" alt="微信截图_20201015132346" src="https://user-images.githubusercontent.com/63178095/96080522-d1811a80-0ee9-11eb-8e3f-edf7606ffa51.png">
删除了这句就不在报这个错误。
安装paddlejs这个插件应该是没有问题的。
<img width="581" alt="微信截图_20201015132549" src="https://user-images.githubusercontent.com/63178095/96080610-02f9e600-0eea-11eb-955b-4f81db05e0d7.png">

**Comment by yueshuangyan** [comment]
使用 import {Runner as paddlejs} from 'paddlejs'

**Comment by zhongkai** [comment]
close this issue cause new version released
