### ISSUE TITLE
希望能给微信小程序上的demo项目

### ISSUE THREAD

**Issue by ninetailskim** [PaddlePaddle/Paddle.js#37]
我已经搞定单张图片的,但过程还是有些艰辛.或者开发人员出一个demo的repo,单独就是小程序端部署的?
另外啥时候能出一个小程序端视频流的方案呢?想做的工作还是偏视频方向的

**Comment by yueshuangyan** [comment]
下周三前给出视频流demo，会追加回复，辛苦等待~

**Comment by ninetailskim** [comment]
> 下周三前给出视频流demo，会追加回复，辛苦等待~

太感动了，终于要来了，我拖延做项目的借口终于要没了~哈哈哈

**Comment by JingyuanZhang** [comment]
已增加 物品识别微信小游 demo

**Comment by JingyuanZhang** [comment]
https://github.com/PaddlePaddle/Paddle.js/tree/master/packages/paddlejs-examples/clasGame
