### ISSUE TITLE
js 推理库过大

### ISSUE THREAD

**Issue by a53769** [PaddlePaddle/Paddle.js#372]
如题，在使用 ocr 示例工程进行检测识别能力的 API 打包时，得到的静态 js 文件有 2.5M 大 。这对于一个前端页面来说还是有点重的，再加上模型文件的大小就更加庞大了。是否有精简压缩的方法，或是否有什么策略可以缓存 js 推理环境。

**Comment by JingyuanZhang** [comment]
主要是因为引入了 opencv，模型后处理用到了；目前 ocr 里面引用的 opencv 已经是定制化删减过 module 版本~ 完整 opencv.js  8M 多~ 我们计划会实现一个不依赖 opencv 的版本，但是优先级较低，如果你着急的话，可以先自己尝试一下用 js 实现 模型后处理部分

**Comment by JingyuanZhang** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/10822846/156704627-bb5c9c03-d6ef-4507-91a1-bf0a1ab10fc9.png">
