### ISSUE TITLE
模型转换后效果太差

### ISSUE THREAD

**Issue by SpectrePrediction** [PaddlePaddle/Paddle.js#388]
我使用的是paddlecls中的MobileNetV2.yaml， 未改动配置（仅仅改动类别以及数据集位置）
训练和预测以及导出后的模型预测都能正常预测且精度正常
但是当我使用
```python
paddlejsconverter --modelPath=./inference/inference.pdmodel --paramPath=./inference/inference.pdiparams --outputDir=./mytest --useGPUOpt=True
```
转换后，并将转换后的模型放在paddle.js时，模型的预测结果完全没有准确度可言
我没找到明显的问题，不知道你能否提供思路？非常感谢

由于上一个问题，我已经改进了我的代码，他能正常预测并且结果不同，他的片段：
```python
/**
   * 通过按钮触发
   */
  test: function(){
    wx.chooseImage({
      count: 1,
      sizeType: ['original'],
      sourceType: ['album', 'camera'],
      success:res => {
        console.log(res)
        this.setData({
          imageSrc: res.tempFilePaths[0]      
        })

        wx.getImageInfo({
          src: res.tempFilePaths[0],
          success: res=> {

            let {width, height, path} = res;

            console.log(width, height)
            let scale = this.data.canvasWidth / width
            console.log(scale)
            width = width * scale
            height = height * scale
            this.setData({
              canvasHeight: height
            })
            
            const ctx = wx.createCanvasContext("myCanvas")
            console.log(ctx)
            ctx.drawImage(path, 0, 0, width, height);
            ctx.draw(false, () => {

              wx.canvasGetImageData({
                canvasId: "myCanvas",
                height: height,
                width: width,
                x: 0,
                y: 0,
                success: res => {

                  // for(let i = 0 ; i < res.data.length; i ++){
                  //   res.data[i] = res.data[i] / 255.0
                  // }
                  // console.log(res.data[100])
                  PaddleJS.predict(res).then(res =>{
                    console.log(res)
                    const max = Math.max.apply(null, res);
                    const index = res.indexOf(max);
                    console.log(index, max)
                    console.log(labelMap[index])
                    if (max >= 0.2){
                      this.setData({
                        buttonText: labelMap[index]
                      })
                    }else{
                      this.setData({
                        buttonText: "没识别出来"
                      })
                    }

                    
                  })
                },
                fail: res => {
                  console.log(res)
                }
  
              },)

            })

          }
        })

      }
    })
  },
```
其中初始化paddle.js的代码为：
模型的地址为本地的模型，使用python -m http.server 80进行挂载
```python
export const PaddleJS = new paddlejs.Runner({
  // modelPath: 'https://mms-voice-fe.cdn.bcebos.com/pdmodel/clas/common/v4_2_0915',
  modelPath: 'http://192.168.3.17',
  // modelPath: 'mod3',
  feedShape: {
      fw: 224,
      fh: 224
  },
  fill: '#fff',
  targetSize: {
      height: 224,
      width: 224
  },
  bgr: false,
  mean: [0.485, 0.456, 0.406],
  std:  [0.229, 0.224, 0.225],
  needPreheat: true,
  webglFeedProcess: true
});
```
我没找到明显的问题，不知道你能否提供思路？非常感谢
如果需要完整代码我将会上传并开源

**Comment by JingyuanZhang** [comment]
提供一下 转换后的模型吧~

**Comment by SpectrePrediction** [comment]
https://www.nullius.cn/wp-content/uploads/2022/03/mod3.zip 需要转换前的模型嘛

**Comment by JingyuanZhang** [comment]
好的 也辛苦提供一下~ 我们对比看一下

**Comment by SpectrePrediction** [comment]
https://www.nullius.cn/wp-content/uploads/2022/03/all_model.zip 这是转换前的模型，非常感谢

**Comment by JingyuanZhang** [comment]
今天稍晚一点反馈

**Comment by SpectrePrediction** [comment]
不急，但我保持期待

**Comment by JingyuanZhang** [comment]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/10822846/156878927-58575a19-5fcb-4f9f-bc14-030267ca8c1a.png">

有算子精度未对齐，我们排查一下

**Comment by SpectrePrediction** [comment]
好的，非常感谢

**Comment by JingyuanZhang** [comment]
已定位，是 paddleClas 模型参数有问题，应该是 引擎里有自动修正机制，所以 paddlepaddle 不会出错，但是转到 paddlejs 就会出错
<img width="947" alt="image" src="https://user-images.githubusercontent.com/10822846/156880042-98126817-c8c3-4bbb-b76b-108861586c44.png">

你把之前转换后的 js 模型 对应 算子 pool2d 的ksize 改成 [7,7]，即可正确推理
<img width="652" alt="image" src="https://user-images.githubusercontent.com/10822846/156880181-8cc49c28-3efa-446e-84ec-c94d7d5ea4ae.png">

可以把相关问题 提到 paddleclas  issue，让他们跟进一下

**Comment by SpectrePrediction** [comment]
好的，我先进行尝试，随后将问题提交到paddleclas的issue，我要取怎么样的标题比较好，辛苦大佬了

**Comment by SpectrePrediction** [comment]
是的，推理成功了，结果非常准确，非常感谢大佬

**Comment by JingyuanZhang** [comment]
问题标题比如：pool2d 算子 ksize 参数有疑问？然后 把我评论里的截图贴一下，或者直接引用这个 issue

**Comment by JingyuanZhang** [comment]
恭喜~！这个模型是你自己训练的吗？可以贴个效果图 看看嘛？

**Comment by JingyuanZhang** [comment]
如果不想模型被公开，可以删除评论里贴的 模型地址 或者文件

**Comment by SpectrePrediction** [comment]
我打算分享到飞桨社区，所以模型会开源（事实上训练的并不好），我正准备前往paddlecls，再三向你致敬

**Comment by JingyuanZhang** [comment]
没事~ 哈哈 ~ 感谢开源~

**Comment by weisy11** [comment]
MobileNetV2使用的是AdaptiveAvgPool2D算子，并不需要设置kernelsize
https://github.com/PaddlePaddle/PaddleClas/blob/8fa820f5c81edb1e7a2b222306a307bc27bff90f/ppcls/arch/backbone/model_zoo/mobilenet_v2.py#L216
算子说明可参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/AdaptiveAvgPool2D_cn.html#adaptiveavgpool2d

**Comment by JingyuanZhang** [comment]
> MobileNetV2使用的是AdaptiveAvgPool2D算子，并不需要设置kernelsize https://github.com/PaddlePaddle/PaddleClas/blob/8fa820f5c81edb1e7a2b222306a307bc27bff90f/ppcls/arch/backbone/model_zoo/mobilenet_v2.py#L216 算子说明可参考： https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/AdaptiveAvgPool2D_cn.html#adaptiveavgpool2d

https://github.com/PaddlePaddle/Paddle.js/pull/395
