### ISSUE TITLE
微信小程序预览时提示“大小超限”，有时会闪退

### ISSUE THREAD

**Issue by chenfh0620** [PaddlePaddle/Paddle.js#39]
代码片段和错误截图如下

**Comment by chenfh0620** [comment]
![image](https://user-images.githubusercontent.com/15808808/100067519-552b1100-2e71-11eb-96bf-ec3f4202e439.png)
![企业微信截图_4b64f4a5-3549-493d-bcd4-eaaf4a2b55b8](https://user-images.githubusercontent.com/15808808/100067614-73910c80-2e71-11eb-9b19-0847763856cd.png)

**Comment by yueshuangyan** [comment]
大小超限只是提示，不影响模型的初始化与预测，闪退问题，能提供一下复现路径吗？

**Comment by hu-qi** [comment]
厉害，原来还有 JS 版本的，给力！值得尝试！
