### ISSUE TITLE
模型转换后的推理结果与转换前差异很大

### ISSUE THREAD

**Issue by luxu1220** [PaddlePaddle/Paddle.js#390]
[picodet_l_640_coco.zip](https://github.com/PaddlePaddle/Paddle.js/files/8202054/picodet_l_640_coco.zip)
上面是 paddle detection 训练结果 
下面是转换成 paddlejs 后的模型
[js3.zip](https://github.com/PaddlePaddle/Paddle.js/files/8202061/js3.zip)

可能同 [#388](https://github.com/PaddlePaddle/Paddle.js/issues/388) 是一个问题？ 

能否用这个测试工具 https://github.com/PaddlePaddle/Paddle.js/issues/388#issuecomment-1059736497  帮忙看看？谢谢

**Comment by JingyuanZhang** [comment]
好的 我们看一下

**Comment by JingyuanZhang** [comment]
确实是 pool2d 算子引起，我们统一做一下升级吧~ 请随时关注 issue 动态哈~

**Comment by luxu1220** [comment]
@JingyuanZhang 已经正常了，多谢

**Comment by xdg2016** [comment]
@luxu1220 你好，我想请教一下，你这个当时用的是哪个版本converter转出来的paddle.js模型，paddledetion版本是多少呢？我这边也在转picodet模型，始终不行
