### ISSUE TITLE
Paddle.js 使用 ch_ppocr_mobile_v1.1 作为模型，发现是缺少 hard_swish，希望增加 hard_swish 算子

### ISSUE THREAD

**Issue by baronhuang** [PaddlePaddle/Paddle.js#40]
Paddle.js 使用 ch_ppocr_mobile_v1.1 作为模型，使用 ModelConverter 转换以后得到的models.json，然后再代码里加载该模型，会报错：
![image](https://user-images.githubusercontent.com/10097495/102796027-95d26780-43e8-11eb-967d-e22b89c8cca6.png)
发现是代码里缺少 hard_swish 算子，希望Paddle团队能早日支持

**Comment by changy1105** [comment]
hard_swish 算子已支持~
