### ISSUE TITLE
Paddlejs--小程序调用模型返回NaN

### ISSUE THREAD

**Issue by Charmnut1** [PaddlePaddle/Paddle.js#404]
小程序 --加载模型（自己训练的ocr文字识别模型）未报错，能返回结果，但全是NaN？
![BB26B52CC965E98F87A0283727819B90](https://user-images.githubusercontent.com/94116018/157832993-1ea0c551-6296-4a70-ae0f-20040e0ebb68.png)

**Comment by JingyuanZhang** [comment]
模型配置可以发一下吗？

**Comment by Charmnut1** [comment]
> 模型配置可以发一下吗？


Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: small
    small_stride: [1, 2, 2, 2]
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 0.00001

**Comment by JingyuanZhang** [comment]
是传给 runner 的 config，先install 最新版本 paddlejs-core 和 webgl ，看下还有无问题，参考 分支 release/2.2.3

**Comment by JingyuanZhang** [comment]
你好，请问还有问题吗？

**Comment by Charmnut1** [comment]
> 你好，请问还有问题吗？

🆗现在有输出了，不是NaN了
