### ISSUE TITLE
GL_INVALID_OPERATION: Uniform type does not match uniform method.

### ISSUE THREAD

**Issue by Carolyn-qxr** [PaddlePaddle/Paddle.js#420]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：

- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）@paddlejs/paddlejs-core 版本：请提供您的 @paddlejs/paddlejs-core 版本 比如 v1.x.x
    2）@paddlejs/paddlejs-backend-webgl 版本：请提供您正在使用的版本
    3）运行环境： 微信小程序 / 百度小程序 / Chrome / Safari / Firefox 等，以及当前版本
    4）系统环境：请您描述系统类型（MAC / Windows）、版本（如Mac OS 10.14），Python版本

- 复现信息：如为报错，请给出复现环境、复现步骤

- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

- 模型文件：原始 paddlepaddle 模型文件 和 paddlejs 模型文件

- 问题代码：可以将代码上传到 gitee 或者 github

**Comment by JingyuanZhang** [comment]
辛苦发一下 模型文件？我们排查下

**Comment by Carolyn-qxr** [comment]
您好，我这边问题已解决，是我自己写的有问题，辛苦你们啦

**Comment by JingyuanZhang** [comment]
ok
