### ISSUE TITLE
pphumanseg模型转换报错

### ISSUE THREAD

**Issue by sp-ljw** [PaddlePaddle/Paddle.js#426]
我使用的是https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/contrib/PP-HumanSeg/README_cn.md 里面给出的pphumanseg_lite_portrait_398x224_with_softmax模型，但是使用convert工具转为js模型时报错了，且无法转换。报错信息如下：
```
============Convert Model Args=============
modelPath:pphumanseg_lite_portrait_398x224_with_softmax/model.pdmodel
paramPath: pphumanseg_lite_portrait_398x224_with_softmax/model.pdiparams
outputDir: ./tmpseg/
enableOptimizeModel: 1
enableLogModelInfo: 0
sliceDataSize:4096
Starting...
Optimizing model...
Loading topology data from pphumanseg_lite_portrait_398x224_with_softmax/model.pdmodel
Loading params data from pphumanseg_lite_portrait_398x224_with_softmax/model.pdiparams
1. Model is successfully loaded!

Optimizing model successfully.

Converting model...
Organizing model operators info...
Organizing model operators info successfully.
Organizing model variables info...
 transpose_10.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_0.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 fill_constant_109.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_20.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_6.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_11.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_0.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_1.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_16.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_18.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_2.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_4.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_2.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_8.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_4.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_5.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_22.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_14.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_12.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_6.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_10.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_7.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_8.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_9.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
Organizing model variables info successfully.
Model chunkNum set successfully.
Model FeedShape set successfully.
['concat_12.tmp_0', 'fill_constant_3.tmp_0', 'fill_constant_5.tmp_0', 'pool2d_0.tmp_0', 'relu_2.tmp_0']
['fill_constant_7.tmp_0', 'fill_constant_9.tmp_0', 'pool2d_0.tmp_0', 'relu_2.tmp_0']
['fill_constant_105.tmp_0', 'fill_constant_107.tmp_0', 'fill_constant_109.tmp_0', 'concat_12.tmp_0', 'fill_constant_3.tmp_0']
['fill_constant_17.tmp_0', 'fill_constant_19.tmp_0', 'concat_12.tmp_0', 'fill_constant_3.tmp_0']
['batch_norm_11.tmp_2', 'fill_constant_23.tmp_0', 'concat_12.tmp_0', 'fill_constant_17.tmp_0', 'fill_constant_19.tmp_0']
A fetal error occured. Failed to convert model.
Traceback (most recent call last):
  File "convertModel.py", line 550, in main
    convertToPaddleJSModel(modelDir, modelName, paramsName, outputDir, useGPUOpt)
  File "convertModel.py", line 509, in convertToPaddleJSModel
    pruningNoSenseTensor(modelInfo)
  File "/root/Desktop/PaddleJS/Paddle.js-release-v2.2.3/packages/paddlejs-converter/pruningModel.py", line 26, in pruningNoSenseTensor
    delLeafOpWithoutChildren(tensorId)
  File "/root/Desktop/PaddleJS/Paddle.js-release-v2.2.3/packages/paddlejs-converter/pruningModel.py", line 46, in delLeafOpWithoutChildren
    del vars[tensorId]
KeyError: 'fill_constant_17.tmp_0'

Cleaning optimized temporary model...
Temporary files has been deleted successfully.
Converting model successfully.
============ALL DONE============
```
请问一下这是什么原因造成的，模型已放附件里了
[pp_humanseg_lite_portrait_398x224_with_softmax.zip](https://github.com/PaddlePaddle/Paddle.js/files/8587888/pp_humanseg_lite_portrait_398x224_with_softmax.zip)

**Comment by JingyuanZhang** [comment]
收到 我们看下

**Comment by sp-ljw** [comment]
> 收到 我们看下

请问一下有进展吗

**Comment by JingyuanZhang** [comment]
[humanseg.zip](https://github.com/PaddlePaddle/Paddle.js/files/8820601/humanseg.zip)
我用最新版本的 paddlejsconverter 转换没有问问题，已转换好
辛苦发一下你是用的paddlejsconverter  版本

**Comment by JingyuanZhang** [comment]
转换后的已发~ 辛苦看下

**Comment by sp-ljw** [comment]
> 转换后的已发~ 辛苦看下

已收到. 我之前是直接使用的paddlejs release v2.2.3中packages/paddlejs-converter/convertToPaddleJSModel.py进行转换的会复现上述的错误。

根据您的描述，本次我使用pip安装PaddleJsConverter 1.0.7得到如下信息：
============Convert Model Args=============
modelPath: ./pphumanseg_lite_portrait_398x224_with_softmax/model.pdmodel
paramPath: ./pphumanseg_lite_portrait_398x224_with_softmax/model.pdiparams
outputDir: ./tmp
enableOptimizeModel: 1
enableLogModelInfo: 0
sliceDataSize:4096
Starting...
Optimizing model...
python paddlelite version: 2.7.1
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0601 23:39:39.806120  2788 opt_base.cc:448] Error: This model is not supported, because 1 ops are not supported on 'arm'. These unsupported ops are: 'bilinear_interp_v2'.

Optimizing model failed.

Converting model...
Organizing model operators info...
Organizing model operators info successfully.
Organizing model variables info...
 transpose_10.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_6.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_12.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_16.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_2.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_20.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_8.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_1.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_18.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_11.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_5.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_0.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_10.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_4.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_3.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_7.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_8.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_9.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_6.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_4.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_2.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_0.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_22.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_14.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
Organizing model variables info successfully.
Model chunkNum set successfully.
Model FeedShape set successfully.
['fill_constant_1.tmp_0', 'fill_constant_3.tmp_0', 'fill_constant_5.tmp_0', 'shape_1.tmp_0_slice_0', 'shape_1.tmp_0_slice_1']
['fill_constant_7.tmp_0', 'fill_constant_9.tmp_0', 'shape_1.tmp_0_slice_0', 'shape_1.tmp_0_slice_1']
['fill_constant_11.tmp_0', 'fill_constant_13.tmp_0', 'fill_constant_15.tmp_0', 'shape_2.tmp_0_slice_0', 'shape_2.tmp_0_slice_1']
['fill_constant_17.tmp_0', 'fill_constant_19.tmp_0', 'shape_2.tmp_0_slice_0', 'shape_2.tmp_0_slice_1']
['fill_constant_21.tmp_0', 'fill_constant_23.tmp_0', 'fill_constant_25.tmp_0', 'shape_3.tmp_0_slice_0', 'shape_3.tmp_0_slice_1']
['fill_constant_27.tmp_0', 'fill_constant_29.tmp_0', 'shape_3.tmp_0_slice_0', 'shape_3.tmp_0_slice_1']
['fill_constant_31.tmp_0', 'fill_constant_33.tmp_0', 'fill_constant_35.tmp_0', 'shape_4.tmp_0_slice_0', 'shape_4.tmp_0_slice_1']
['fill_constant_37.tmp_0', 'fill_constant_39.tmp_0', 'shape_4.tmp_0_slice_0', 'shape_4.tmp_0_slice_1']
['fill_constant_41.tmp_0', 'fill_constant_43.tmp_0', 'fill_constant_45.tmp_0', 'shape_5.tmp_0_slice_0', 'shape_5.tmp_0_slice_1']
['fill_constant_47.tmp_0', 'fill_constant_49.tmp_0', 'shape_5.tmp_0_slice_0', 'shape_5.tmp_0_slice_1']
['fill_constant_51.tmp_0', 'fill_constant_53.tmp_0', 'fill_constant_55.tmp_0', 'shape_6.tmp_0_slice_0', 'shape_6.tmp_0_slice_1']
['fill_constant_57.tmp_0', 'fill_constant_59.tmp_0', 'shape_6.tmp_0_slice_0', 'shape_6.tmp_0_slice_1']
['fill_constant_61.tmp_0', 'fill_constant_63.tmp_0', 'fill_constant_65.tmp_0', 'shape_7.tmp_0_slice_0', 'shape_7.tmp_0_slice_1']
['fill_constant_67.tmp_0', 'fill_constant_69.tmp_0', 'shape_7.tmp_0_slice_0', 'shape_7.tmp_0_slice_1']
['fill_constant_71.tmp_0', 'fill_constant_73.tmp_0', 'fill_constant_75.tmp_0', 'shape_8.tmp_0_slice_0', 'shape_8.tmp_0_slice_1']
['fill_constant_77.tmp_0', 'fill_constant_79.tmp_0', 'shape_8.tmp_0_slice_0', 'shape_8.tmp_0_slice_1']
['fill_constant_81.tmp_0', 'fill_constant_83.tmp_0', 'fill_constant_85.tmp_0', 'shape_9.tmp_0_slice_0', 'shape_9.tmp_0_slice_1']
['fill_constant_87.tmp_0', 'fill_constant_89.tmp_0', 'shape_9.tmp_0_slice_0', 'shape_9.tmp_0_slice_1']
['fill_constant_91.tmp_0', 'fill_constant_93.tmp_0', 'fill_constant_95.tmp_0', 'shape_10.tmp_0_slice_0', 'shape_10.tmp_0_slice_1']
['fill_constant_97.tmp_0', 'fill_constant_99.tmp_0', 'shape_10.tmp_0_slice_0', 'shape_10.tmp_0_slice_1']
['fill_constant_101.tmp_0', 'fill_constant_103.tmp_0', 'fill_constant_105.tmp_0', 'shape_11.tmp_0_slice_0', 'shape_11.tmp_0_slice_1']
['fill_constant_107.tmp_0', 'fill_constant_109.tmp_0', 'shape_11.tmp_0_slice_0', 'shape_11.tmp_0_slice_1']
['fill_constant_111.tmp_0', 'fill_constant_113.tmp_0', 'fill_constant_115.tmp_0', 'shape_12.tmp_0_slice_0', 'shape_12.tmp_0_slice_1']
['fill_constant_117.tmp_0', 'fill_constant_119.tmp_0', 'shape_12.tmp_0_slice_0', 'shape_12.tmp_0_slice_1']
['shape_13.tmp_0_slice_0']
['shape_0.tmp_0_slice_0']
Dumping model structure to json file...
Dumping model structure to json file successfully
Output No.1 binary file, remain 0 param values.
Slicing data to binary files successfully. (1 output files and 137466 param values)
Temporary files has been deleted successfully.
Converting model successfully.
============ALL DONE============

转换后可以得到与您相同的结果，还有两个问题1.这个Optimizing model failed是否只是算子没有换成更优的，实际还是可以使用的呢。2.安装 paddlejsconverter会强制依赖paddlelite的2.7版本，是否这个关联的版本太老了。
