### ISSUE TITLE
Type def for paddle.js

### ISSUE THREAD

**Issue by Edward-Zhou** [PaddlePaddle/Paddle.js#436]
请问下如何为paddle.js创建type def.

在导入`@paddlejs-models/ocr`得到以下的错误

![image](https://user-images.githubusercontent.com/16079555/169953045-d50faa02-4d22-493c-8749-ed8630f661bd.png)

**Comment by JingyuanZhang** [comment]
项目里新建一个 typing.d.ts 或者 global.d.ts 里声明 declare module '@paddlejs-models/ocr';
