### ISSUE TITLE
使用vite时报错 opencv_ocr.js:46 Uncaught ReferenceError: Module is not defined

### ISSUE THREAD

**Issue by chenqianhe** [PaddlePaddle/Paddle.js#472]
使用vite时会有针对 opencv_ocr.js 的报错

```
opencv_ocr.js:46 Uncaught ReferenceError: Module is not defined
    at opencv_ocr.js:46:5
    at opencv_ocr.js:11:22
    at node_modules/@paddlejs-mediapipe/opencv/library/opencv_ocr.js (opencv_ocr.js:22:1)
    at __require (chunk-RSJERJUL.js?v=aa02e290:3:50)
    at dep:@paddlejs-mediapipe_opencv_library_opencv_ocr:1:16
```

**Comment by zlq4863947** [comment]
我也报这个错

**Comment by chenqianhe** [comment]
> 我也报这个错

https://github.com/PaddlePaddle/FastDeploy/blob/17a118919913a3c84b57940b9e0a5c19b2835f37/examples/application/js/web_demo/src/pages/cv/ocr/TextRecognition/index.html#L4

我把整个都重新搞了下；但是cv这个没源码，问题只能这么解决

**Comment by zlq4863947** [comment]
> > 我也报这个错
> 
> https://github.com/PaddlePaddle/FastDeploy/blob/17a118919913a3c84b57940b9e0a5c19b2835f37/examples/application/js/web_demo/src/pages/cv/ocr/TextRecognition/index.html#L4
> 
> 我把整个都重新搞了下；但是cv这个没源码，问题只能这么解决

非常感谢，醍醐灌顶啊，终于解决了这个问题！！

**Comment by Banqc0621** [comment]
没看明白，是怎样解决的呢？

**Comment by Drake-Rabbit** [comment]
厉害，我引入paddle.js，控制台这个也报这个错 index.js:1  Uncaught ReferenceError: Module is not defined
加了<script>var Module;</script>就好了

**Comment by Drake-Rabbit** [comment]
厉害，加了<script>var Module;</script>就好了
