### ISSUE TITLE
新建项目导入 ocr包提示找不到模块

### ISSUE THREAD

**Issue by Gsonovb** [PaddlePaddle/Paddle.js#479]
看了OCR说明文档， 和NPM上包说明，都只说导入 @paddle-js-models/ocr 。

但只要执行代码，就会收到  Module is not defined

所以到底还需要导入什么？

**Comment by Wudax** [comment]
我和你一样的问题，也是报错

**Comment by chenqianhe** [comment]
需要在html中加入 `<script>var Module;</script>`

参考https://github.com/PaddlePaddle/FastDeploy/blob/9531e99948cd1605e95a8ad2f7194831a9910e98/examples/application/js/web_demo/src/pages/cv/ocr/TextRecognition/index.html#L4

项目实例在

https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/application/js

**Comment by Wudax** [comment]
非常感谢你的帮助



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qianhe ***@***.***&gt;; 
发送时间: 2022年12月2日(星期五) 下午3:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle.js] 新建项目导入 ocr包提示找不到模块 (Issue #479)





 
需要在html中加入 <script&gt;var Module;</script&gt;
 
参考https://github.com/PaddlePaddle/FastDeploy/blob/9531e99948cd1605e95a8ad2f7194831a9910e98/examples/application/js/web_demo/src/pages/cv/ocr/TextRecognition/index.html#L4
 
项目实例在
 
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/application/js

**Comment by Gsonovb** [comment]
感谢， 这个隐藏的太深了。

不过测试一下，再虚机里面没有GPU，打开直接失败。
再物理机测试，图片太大话，会吃爆内存，然后Chrome 强制关闭页面。
