### ISSUE TITLE
safari:SyntaxError: Unexpected EOF

### ISSUE THREAD

**Issue by hktalent** [PaddlePaddle/Paddle.js#504]
yarn build
out ocr.js

```
$(document).ready(function(){
if(window.bEabOcr && !window.ocrLoad)window.ocrLoad=true,fnTmp89(),$("body").append("<script src=/js/ocr.js></scr"+"ipt>");
});
```
safari:SyntaxError: Unexpected EOF
<img width="733" alt="image" src="https://github.com/PaddlePaddle/Paddle.js/assets/18223385/2825b56a-62bd-4dbf-b936-086e1bf02f17">

**Comment by talatkuyuk** [comment]
How did you solve? I am facing the same error.

**Comment by hktalent** [comment]
@talatkuyuk 
```
const Is=e=>{var a=document.createElement("script");a.src=e,a.defer=!1,document.head.appendChild(a)}
```
more see:
https://chat.51pwn.com:2083/?cnId=51pwn&atRd=true&showme=true&eAi=true&startChat=1
