### ISSUE TITLE
希望提供 ”OCR图像中文字识别“ 的例子

### ISSUE THREAD

**Issue by czs0906** [PaddlePaddle/Paddle.js#78]

**Comment by liuna471658955** [comment]
同求这个例子

**Comment by 60999** [comment]
同求

**Comment by macqueen09** [comment]
mark

**Comment by changy1105** [comment]
已支持paddleOCR 文本检测ch_ppocr_mobile_v2.0_det模型，正在跟进 文本识别ch_ppocr_mobile_v2.0_rec 模型。模型链接如下：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/models_list.md（ch_ppocr_mobile_v2.0_det）

**Comment by liuxin2533** [comment]
请问有进展了吗

> 已支持paddleOCR 文本检测ch_ppocr_mobile_v2.0_det模型，正在跟进 文本识别ch_ppocr_mobile_v2.0_rec 模型。模型链接如下：[https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/models_list.md（ch_ppocr_mobile_v2.0_det）](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/models_list.md%EF%BC%88ch_ppocr_mobile_v2.0_det%EF%BC%89)

**Comment by HopeFE** [comment]
同问有进展了么

**Comment by QianLingjun** [comment]
同问，感谢

**Comment by JingyuanZhang** [comment]
已支持 
https://github.com/PaddlePaddle/Paddle.js/tree/master/packages/paddlejs-models/ocr
